[twitter]
api_key = "d3J6aAeWb9rreaK0ntxQ7zLGq"
api_secret_key = "IQQXFxkDsvcCcj8Ekp6JJCys32XhtUp0ZxFvYIG7ISKChaI6yh"
access_token = "1715839728560361472-1tdOCeCsX2cWtFGMBEAT5ucxAQ4r4q"
access_token_secret = "wBk3ZRIvrZHzVNdai2adWK2utMn2KmOaUoPJvlaXN0KIM"
