[twitter]
api_key = "bdZKuVZyeKYkW75mku3f3H10i"
api_secret_key = "5CZgRf2TyWhHAs4onpwfg6UepWfbcT1z854BWxqiJjwxwENX6w"
access_token = "1715839728560361472-ZVysr9vBee1hy5vmCpRo6G1pt5Cd8c"
access_token_secret = "nPjZSs93UJ5hbAhtT9OlY80BhsrvGorZLmxadTeXiCtz9"
bearer_token = "AAAAAAAAAAAAAAAAAAAAAJCwuQEAAAAAVIXeygVWF5Lj7E7Ha9SsJU2%2BQm8%3DSqSRkjbZ8hDZoQ4AjemOQgEYU8KE0xmMw5g3FpylRUmf6TvVLr"
